spring:
  application:
    name: todoback
  datasource:
    url: ${H2_URL}
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true